version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "23:30"
      timezone: "Europe/London"
    commit-message:
      # Prefix all commit messages with "build: "
      prefix: "build"
    pull-request-branch-name:
      # Change the default separator (/) to a hyphen (-)
      separator: "-"
